### ISSUE TITLE
Some of the images are poor

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#23]
I know the plan is to replace all of the images, but I thought I'd note the ones that stand out in one issue.

**Comment by hen** [comment]
Acid Storm's image is blurry.

**Comment by zz1000zz** [comment]
Feel free to note any that stand out in particular.  The plan is to redo all the images, but until that gets done, individual ones can be fixed.

**Comment by hen** [comment]
Field Repair is especially bad.
