### ISSUE TITLE
Error in Play Characters

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#26]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hen\AppData\Local\Programs\OCTGN\Data\GameDatabase\f44befce-4d6d-4fb9-a286-9585f36aece9\scripts\actions.py", line 390, in playCharacters
ValueError: invalid literal for int() with base 10: ''

playCharacters(Pile(16842756, 'Characters', Player(1)))

**Comment by hen** [comment]
Deck was:

    <card qty="1" id="f6f88efc-e457-4a6d-8a28-143129e75a3d">Brawn - Demolitions</card>
    <card qty="1" id="e81e285b-bbda-42c3-9471-f7e1ca94f027">Autobot Outback - Gunner</card>
    <card qty="1" id="cd089d15-ea99-4ced-bb21-d8c9ac70f1c0">Autobot Gears - Transport &amp; Reconnaissance</card>
    <card qty="1" id="3f8a6b96-2bc4-4e67-ab7a-272f56b4348b">Private Powertrain - Off-Road Patrol, Patrol Leader</card>
    <card qty="1" id="c758efd9-5c60-4b54-b25b-922f9472d154">Systems Enhancement</card>
    <card qty="1" id="07618782-2e57-42dc-a4bc-d8aeb0d0c197">Resilience</card>
    <card qty="1" id="a1bd9485-f8af-4f0e-bbcd-69a82f704588">High Five</card>

**Comment by hen** [comment]
Ah. High Five is a battle card :)

**Comment by hen** [comment]
Enhancement request: Don't code error when a zero-star card is illegally in the Characters pile.
Low priority.

**Comment by zz1000zz** [comment]
The code for that function has been changed a bit.  Uncertain if the change will address this enhancement request.  Would be good if testing could confirm one way or another.

**Comment by zz1000zz** [comment]
Having not received any further reports of this, will assume the changes to the function addressed the request.  If not, this ticket can be reopened later or a new ticket can be created.
