### ISSUE TITLE
Battlemaster support

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#38]
When you KO a Battlemaster; heal it and switch modes.
When a Battlemaster is played; switch modes.

Same for Weaponizers?

**Comment by hen** [comment]
KO code (adding around the start of the KO function):

    # Instead of KO'ing, flip the character to upgrade mode and heal it
    def flipCharacterToUpgrade(card):
        awaken(card)
        card.markers[CounterMarker] = 0
    
    def KO(card, x=0, y=0):
        mute()
    
        if( ("Battle Master" in card.trait and card.alternate == card.alternates[1]) or "Sergeant Cog - Artillery, Mechanic" in card.name):
            flipCharacterToUpgrade(card)
            return

**Comment by hen** [comment]
Playing a BattleMaster in the right mode is probably best handled by changing the data so the Bot mode is the default.

**Comment by zz1000zz** [comment]
Data schema will be changed in an upcoming update to make things like this easier to implement.  Given the upcoming changes, there's little sense in making a function like this now.  Closing the issue until the data schema is updated.  If code addressing this issue isn't included along with the schema update, will reopen.
