### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#45]
Dinobot Slug Hot-Header Warrior   (Headed)
  Deadlock Soldier Of Fortune   (lowercase the Of)
  TTC-HP Oblivion Launchera  (should be Oblivio)
  War Of Attrition  (lower the Of)
  Captain Wheeljack Engineer Scientist   (Engineering)
  Erractic Lightning (Erratic)
  Heavy Handed (Heavy-Handed)
  MTX-M2 Anit-Gravity Cannon  (Anti)
  One Shall Stand One Shall Fall  (One Shall Stand, One Shall Fall)
  Raider Brunt Weapon Soldier (Weapons)   (or 'Weapons, Soldier')
  RR Disruption Blade  (Disruptor)  (Known issue)
  Sergeant Six-Gun  (Missing: Artillery Soldier)  (or missing:  Artillery, Soldier)
  Starscream Scheming Second-In-Command  (in)

**Comment by zz1000zz** [comment]
The proposed One Shall Stand, One Shall Fall change appears to already be in place.

**Comment by zz1000zz** [comment]
Errors corrected for next cardlist update.  May not be in immediate OCTGN update.
