### ISSUE TITLE
Faction Battle Cards

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#5]
The following have faction icons on the images but don't have a faction field filled in

Autobots:
  Aerialbot Enigma
  Aerialbot Formation
  Combat Commands
  Confidence
  Dinobot Enigma
  Electrified Spikes
  Field Repair
  Press the Advantage
  Sentinel Enigma
  Agility of Bumblebee
  Ion Blaster of Optimus Prime
  Matrix of Leadership
  Static Laser of Ironhide
  Protected by Metroplex
  Rally the City

Decepticon:
  Bad Attitude
  Predacon Enigma
  Stunticon Enigma
  Stunticon Swagger
  Swindled
  Underhanded Tactics
  Construction Enigma
  Heavy Landing
  Reclaim
  Firecon Flame
  Fusion Cannon of Megatron
  Null-Ray of Starscream

**Comment by zz1000zz** [comment]
Thanks, these should all be fixed in the next update.
