### ISSUE TITLE
Stratagems are scooped to the Deck

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#53]
When you scoop, strategems get shuffled into the battle deck, not returned to characters.

**Comment by hen** [comment]
Looks like:

    or card.Type=="Stratagem"

needs to be added to:

    480     if card.Type=="Character" or len(card.alternates) > 1:

**Comment by zz1000zz** [comment]
Forgot about the Scoop function needed to be expanded to catch Stratagems.  Proposed fix will be included in the next update.
