### ISSUE TITLE
Playing Heads shows their ID

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#54]
When you play a Head, it asks you which head you wish to place on <window of characters>; however it refers to them by a numerical ref ID instead of name.

Looks like this code needs a card.name instead of card:

445     dlg.title = "Choosing a bot to put your {} on.".format(card)
446     dlg.text = "Please select a body to put your {} on".format(card)

**Comment by zz1000zz** [comment]
Fix will be included in the next update.
